name: New Hire onboarding deployment
description: Create onboarding issues and project board for new hire
title: "[New Hire]: "
labels: ["new-hire"]
body:
  - type: markdown
    attributes:
      value: |
        Complete the fields below, and submitting the issue will trigger GitHub Actions to create the new-hire repository, issues, and project board. A link will be added to as a comment to this issue once complete.
  - type: input
    id: new-handle
    attributes:
      label: New Hire handle
    validations:
      required: true
  - type: checkboxes
    id: target
    attributes:
      label: Where should the repository be created?
      validations:
        required: true
      options:
        - label: github.com/github/support-onboarding-[handle]
        - label: ghe.io/new-hires/[handle]
  - type: checkboxes
    id: role
    attributes:
      label: What role does new hire have? (closest fit - pick only one)
      validations:
        required: true
      options:
        - label: Support Engineer - Security and Revenue
        - label: Support Engineer - Technical Support
        - label: Support Engineer - Enterprise Support
        - label: Support Engineer - Premium Support
        - label: Support Engineer - Customer Reliability Engineer
        - label: Support Engineer - GHAE
        - label: Support Contractors
