on:
  pull_request:
    branches:
    - master
  pull_request_review:
    branches:
    - master
jobs:
  meh:
    runs-on: ubuntu-latest
    steps:
    - uses: fkirc/skip-duplicate-actions@master
    - run: |
        echo "heya"
        sleep 120s
        echo "done"
        
