on: workflow_dispatch
jobs:
  jobby:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2.3.4
    
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          server-id: github
        
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Configure NPM Package, Maven-public
        run: |
          set +x
          ARTIFACTORY_CRED=`echo -n "${{ secrets.ARTIFACTORY_CRED_USR }}:${{ secrets.ARTIFACTORY_CRED_KEY }}" | openssl enc -A -base64`
          npm config set registry https://packages.aa.com/artifactory/nodejs.org-proxy/dist/
          npm config set _auth $ARTIFACTORY_CRED
          npm config set registry https://packages.aa.com/artifactory/registry.npmjs-proxy/npm/-/
          npm config set _auth $ARTIFACTORY_CRED
          npm config set registry https://packages.aa.com/artifactory/api/npm/npm-public/
          npm config set _auth $ARTIFACTORY_CRED
          set -x
          
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1.2.0
        with:
          version: 1.50.2
          
      - name: SetUp Application Version
        run: |
          echo "Workspace is $GITHUB_WORKSPACE"
          # cat $GITHUB_WORKSPACE/settings.xml
          mvn versions:set versions:update-child-modules -s $GITHUB_WORKSPACE/settings.xml -DnewVersion=$APPLICATION_VERSION -DprocessAllModule
