name: cant cancel 2nd job
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "started"
      - run: sleep 120
      - run: echo "ended"
  job2:
    needs: job1
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "started"
      - run: sleep 120
      - run: echo "ended"
