name: concurrency_approval_500
on: workflow_dispatch
jobs:
  prod-infraconcurrency_approval_500gke-apply:
    environment: require approval
    concurrency: concurrency_approval_500
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "start"
          sleep 120
          echo "end"
          
