on: push
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git clone --single-branch --branch ${{ github.ref }} https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
