on: [workflow_dispatch]
jobs:
  inactive_users:
    runs-on: ubuntu-latest
    env:
      OCTOKIT_ACCESS_TOKEN: 00000000000000000000000
    steps:
      - run: |
          echo "OCTOKIT_ACCESS_TOKEN=${{ secrets.ORGANIZATION_PAT }}" >> $GITHUB_ENV
          echo "FROM_DATE=$(date -d "$date -5 days" +"%Y%m%d")" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: github/platform-samples
      - run: cd api/ruby/find-inactive-members
      - run: gem install octokit -N --silent
      - run: ruby find_inactive_members.rb --check --email --verbose -o ${{ github.repository_owner }} -d FROM_DATE
