name: inactive org users
on: [workflow_dispatch]
jobs:
  inactive_users:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "OCTOKIT_ACCESS_TOKEN=${{ secrets.TIMBURGAN_PAT }}" >> $GITHUB_ENV
          echo "FROM_DATE=$(date -d "$date -5 days" +"%Y%m%d")" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: github/platform-samples
      - run: sudo gem install octokit -N --silent
      - run: ls -la
      - run: |
          cd api/ruby/find-inactive-members
          ruby find_inactive_members.rb --email --organization ${{ github.repository_owner }} --date $FROM_DATE
