on:
  release:
    types: [released]
    
jobs:
  example_job:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'master'
    steps:
    - uses: timburganec/checkout@v2
    - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
