on:
  release:
    types: [released]
    
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - uses: timburganec/checkout@v2
    - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
