name: quoted contexts
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - run: echo $INPUT_IMAGE_NAME
      with: 
        image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.id }}:latest
  second:
    runs-on: ubuntu-latest
    steps:
    - run: echo $INPUT_IMAGE_NAME
      with: 
        image-name: 'ghcr.io/${{ github.repository }}/${{ github.event.repository.id }}:latest'
