name: Test Ping
on:
  push: #pull_request_target:
    branches: [ master ]
    #paths: test/**
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
      - run: echo "heyhey"
