name: Test Ping
on:
  push: #pull_request_target:
    branches: [ master ]
    #paths: test/**
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
