name: artifact approvals
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    environment: require approval
    steps:
    - run: echo hello > my_artifact.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my_artifact
        path: my_artifact.txt
